name: 'CI/CD: Build, Publish and Deploy App'

on:
  push:
    branches:
      - develop

jobs:
  build-and-publish:
    name: Build and Publish to Nexus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Docker for insecure registry
        run: |
          echo '{ "insecure-registries":["18.207.189.45:8082"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: http://18.207.189.45:8082
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t 18.207.189.45:8082/docker-repo/store-api:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push 18.207.189.45:8082/docker-repo/store-api:${{ github.sha }}

  deploy:
    name: Deploy Full Stack to EC2
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy project files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yaml,prometheus.yml"
          target: "~/app"

      - name: Deploy services on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export API_VERSION=${{ github.sha }}
            cd ~/app
            docker login http://18.207.189.45:8082 -u ${{ secrets.NEXUS_USERNAME }} -p ${{ secrets.NEXUS_PASSWORD }}
            docker-compose pull
            docker-compose up -d --remove-orphans
